name: check_coverage
description: A tiny Dart CLI tool to check if code coverage is below the threshold. Analyzes the tracefile used by lcov.
repository: https://github.com/f3ath/check-coverage
version: 0.0.5

executables:
  check_coverage: check_coverage

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  lcov_tracefile: ^0.0.1

dev_dependencies:
  test: ^1.21.5

cider:
  link_template:
    tag: https://github.com/f3ath/check-coverage/releases/tag/%tag% # initial release link template
    diff: https://github.com/f3ath/check-coverage/compare/%from%...%to% # subsequent releases link template
