name: check_coverage
description: A tiny Dart CLI tool to check if code coverage is below the threshold. Analyzes the tracefile used by lcov.
repository: https://github.com/f3ath/check-coverage
version: 0.0.1

executables:
  check_coverage: check_coverage

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.7