name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  dart:stable
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Formatter
        run: dart format --output none --set-exit-if-changed example lib test
      - name: Analyzer
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Tests
        run: dart test
